### ISSUE TITLE
Root Requirements

### ISSUE THREAD

**Issue by TomBayne** [5GSD/AICDm#6]
Why does this require root, the previous version did not need this?

**Comment by MinIsMin** [comment]
From the [readme](https://github.com/5GSD/AICDm/blob/a54f830b69a40639af0885bfb24fd9ab30c34004/README.md#app-permissions):

`In addition (to the app permissions), the app require root privileges, which are only used to access the /dev/diag interface from which the baseband network information is read.`

But root is not absolutely necessary (in the final version) because the [development criteria](https://github.com/5GSD/AICDm/blob/a54f830b69a40639af0885bfb24fd9ab30c34004/README.md#development-criteria) states:
`AICD will offer partial support for non-rooted devices`

**Comment by beerisgood** [comment]
That sounds good! I switch to a root-less state because of security

**Comment by E3V3A** [comment]
> That sounds good! I switch to a root-less state because of security

Not sure what you think "security" is, here. But surely a properly configured (firewall, default DNS, bloat removal etc)  rooted device is far more secure than the bloated spyware infected off the shelf Androids. And if you're interested in this app, then root should be default. The only reason I suggested not to force people having root is that we hope to integrate the app into the OS as a system app for selected OEMs. In addition if you want a standard AOS app to read anything useful from radio interface, you have to be root!

**Comment by beerisgood** [comment]
Root isnt required if the ROM isnt bloated. See LineageOS
Also root is always a security risk!
